name: raktkhoj
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #flutter_dialogflow: ^0.1.3
  cupertino_icons: ^1.0.2
  #fluro: "^1.3.1"
  fluro: ^2.0.3
  meta: ^1.0.2
  carousel_pro: ^1.0.0
  #http support
  http: ^0.13.3
  #syncfusion_flutter_pdf: ^19.2.51-beta
  path_provider: ^2.0.8
  open_file: ^3.2.1

  # display PDF
  flutter_pdfview: ^1.0.4





  #for viewing pdf
  #advance_pdf_viewer: any
  #syncfusion_flutter_pdfviewer: ^19.3.59-beta
#  permission_handler: any
  simple_animations: ^1.3.3
  custom_navigation_bar: ^0.8.2
  clay_containers: ^0.2.2
  get: ^4.6.1
  get_storage: ^2.0.3
  shimmer: ^1.0.1
  curved_navigation_bar: ^0.3.4
  carousel_slider: ^2.3.1
  google_fonts: ^2.1.0
  firebase_core: ^1.10.6
  firebase_auth: ^3.1.3
  firebase_database: ^9.0.4
  cloud_firestore: ^2.5.3
  modal_progress_hud: ^0.1.3
  pinput: ^0.2.6
  flutter_svg: ^0.22.0
  dropdownfield: ^1.0.3
  image_picker: ^0.8.4+4
  firebase_storage: ^10.0.5
  cached_network_image: ^3.1.0
  path: ^1.7.0
  #path_provider: ^1.6.22
  #url_launcher: ^5.7.8
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.0.17
  google_maps_flutter: ^2.1.1
  geolocator: ^5.1.2
  emoji_picker_flutter: ^1.0.8
  provider:
  emoji_picker: ^0.0.2
  file_picker: ^4.3.0
  share: ^2.0.4
  firebase_dynamic_links: ^0.5.0+11

  unicorndial: ^1.1.5
  onesignal_flutter: ^3.2.7
  mailer: ^5.0.2
  flutter_ringtone_player: ^3.1.1
  dialog_flowtter: ^0.3.1
  agora_rtc_engine: ^4.0.7






dev_dependencies:
  flutter_test:
    sdk: flutter
  #firebase_auth: ^3.1.3

  google_sign_in: ^5.1.1
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.8



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - customStyle
    - assets/sample.pdf




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages